In [1]:
## importing all requirde libraries ##

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('C:\\Users\\91782\\Downloads\\gesture+phase+segmentation (1)\\a1_raw.csv')

In [3]:
df.head()

lhx       lhy       lhz       rhx       rhy       rhz        hx  \
0  5.347435  4.363681  1.501913  5.258967  4.319263  1.488703  5.037871   
1  4.869622  4.254210  1.556133  5.240113  4.346338  1.554309  5.037610   
2  5.357447  4.364039  1.500969  5.238928  4.347924  1.554150  5.037514   
3  4.942886  4.281878  1.546513  5.111436  4.229660  1.527091  5.037526   
4  5.003160  4.278530  1.542866  4.985812  4.182155  1.520330  5.037557   

         hy        hz        sx        sy        sz       lwx       lwy  \
0  1.618295  1.778350  5.062803  4.229656  1.772577  4.972902  4.301065   
1  1.618370  1.778573  5.061430  4.228504  1.772859  4.974908  4.303656   
2  1.618298  1.778774  5.059245  4.228004  1.773568  4.981612  4.305363   
3  1.618612  1.778855  5.056475  4.226891  1.774519  4.987158  4.304063   
4  1.619226  1.778925  5.052367  4.225485  1.775536  4.983912  4.296833   

        lwz       rwx       rwy       rwz  timestamp phase  
0  1.564781  5.553945  4.370456  1.553521    5702026  Rest  
1  1.565527  5.423875  4.303708  1.569942    5702058  Rest  
2  1.563643  5.332170  4.438061  1.572841    5702089  Rest  
3  1.565929  5.311104  4.396774  1.566368    5702120  Rest  
4  1.569889  5.193762  4.335417  1.560144    5702167  Rest

In [4]:
df.columns

Index(['lhx', 'lhy', 'lhz', 'rhx', 'rhy', 'rhz', 'hx', 'hy', 'hz', 'sx', 'sy',
       'sz', 'lwx', 'lwy', 'lwz', 'rwx', 'rwy', 'rwz', 'timestamp', 'phase'],
      dtype='object')

In [5]:
le=LabelEncoder()
df.phase=le.fit_transform(df.phase)
df.head()

lhx       lhy       lhz       rhx       rhy       rhz        hx  \
0  5.347435  4.363681  1.501913  5.258967  4.319263  1.488703  5.037871   
1  4.869622  4.254210  1.556133  5.240113  4.346338  1.554309  5.037610   
2  5.357447  4.364039  1.500969  5.238928  4.347924  1.554150  5.037514   
3  4.942886  4.281878  1.546513  5.111436  4.229660  1.527091  5.037526   
4  5.003160  4.278530  1.542866  4.985812  4.182155  1.520330  5.037557   

         hy        hz        sx        sy        sz       lwx       lwy  \
0  1.618295  1.778350  5.062803  4.229656  1.772577  4.972902  4.301065   
1  1.618370  1.778573  5.061430  4.228504  1.772859  4.974908  4.303656   
2  1.618298  1.778774  5.059245  4.228004  1.773568  4.981612  4.305363   
3  1.618612  1.778855  5.056475  4.226891  1.774519  4.987158  4.304063   
4  1.619226  1.778925  5.052367  4.225485  1.775536  4.983912  4.296833   

        lwz       rwx       rwy       rwz  timestamp  phase  
0  1.564781  5.553945  4.370456  1.553521    5702026      2  
1  1.565527  5.423875  4.303708  1.569942    5702058      2  
2  1.563643  5.332170  4.438061  1.572841    5702089      2  
3  1.565929  5.311104  4.396774  1.566368    5702120      2  
4  1.569889  5.193762  4.335417  1.560144    5702167      2

In [6]:
df.columns
data=df[['lhx', 'lhy', 'lhz', 'rhx', 'rhy', 'rhz', 'hx', 'hy', 'hz', 'sx', 'sy',
       'sz', 'lwx', 'lwy', 'lwz', 'rwx', 'rwy', 'rwz', 'timestamp']]

#independent var(Data)
X=np.asarray(data)

#dependent var(target)
y=np.asarray(df['phase'])

X.shape
y.shape

(1747,)

In [7]:
# Training the datasrt
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape
X_test.shape
y_train.shape
y_test.shape


(350,)

In [8]:
####-------------------Classification----------------###
# importing all requirde libraries and modules
from sklearn.linear_model import Perceptron
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB


# Giving Parameters to the fumctions
clf1=KNeighborsClassifier(n_neighbors=5,metric="minkowski")
clf2=SVC(C=1.0,kernel="rbf")
clf3=GaussianNB(priors=None)
clf4=Perceptron(alpha=0,l1_ratio=0.15,max_iter=100)
clf5=DecisionTreeClassifier(criterion="gini",splitter="best", max_depth=5)


clf=[clf1,clf2,clf3,clf4,clf5]
clf_name=["kneighbors","svc","gaussionNB","perceptron","decisiontree"]

from sklearn.metrics import accuracy_score 
accuracy={}


# Calling all the functions
for model,model_name in zip(clf,clf_name):
    model.fit(X_train,y_train)                  # Fit the classifier to the training data
    prediction=model.predict(X_test)            # Make predictions on the test set
    accuracy[model_name]=accuracy_score(y_test,prediction)
    
    
for i,j in accuracy.items():
    print(i,":-",j)

kneighbors :- 0.9742857142857143
svc :- 0.4
gaussionNB :- 0.7028571428571428
perceptron :- 0.40285714285714286
decisiontree :- 0.8371428571428572


In [9]:
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.cluster import Birch

clustering_algorithms = {
    'K-Means': KMeans(n_clusters=5),
    'Agglomerative': AgglomerativeClustering(n_clusters=5),
    'DBSCAN': DBSCAN(eps=0.5, min_samples=5),
    'GMM': GaussianMixture(n_components=5),
    'BIRCH': Birch(n_clusters=5)
}

data = df

for algorithm_name, algorithm in clustering_algorithms.items():
    labels = algorithm.fit_predict(data)
    print(f"Algorithm: {algorithm_name}")
    print("Cluster Labels:")
    print(labels)
    print("------")


Algorithm: K-Means
Cluster Labels:
[4 4 4 ... 2 2 2]
------
Algorithm: Agglomerative
Cluster Labels:
[1 1 1 ... 3 3 3]
------
Algorithm: DBSCAN
Cluster Labels:
[-1 -1 -1 ... -1 -1 -1]
------
Algorithm: GMM
Cluster Labels:
[4 4 4 ... 0 0 0]
------
Algorithm: BIRCH
Cluster Labels:
[1 1 1 ... 3 3 3]
------
